import { cert, getApps, initializeApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore } from 'firebase-admin/firestore';
function init(){ if(getApps().length)return; const raw=process.env.FIREBASE_SERVICE_ACCOUNT_KEY; if(!raw)throw new Error('FIREBASE_SERVICE_ACCOUNT_KEY is not configured'); initializeApp({credential:cert(JSON.parse(raw))}); }
function iso(v){return v?.toDate?v.toDate().toISOString():String(v||'');}
function premiumActive(u){const t=Date.parse(iso(u.premiumUntil));return Number.isFinite(t)&&t>Date.now();}
export default async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
 try{init();const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim();const decoded=await getAuth().verifyIdToken(token);const db=getFirestore();const snap=await db.collection('users').doc(decoded.uid).get();if(!snap.exists)return res.status(404).json({error:'Профиль не найден'});const user=snap.data();if(!premiumActive(user)||user.isVerified!==true)return res.status(403).json({error:'Публикация недоступна: нужен активный Premium и верификация.'});const content=String(req.body?.content||'').trim(),sportTag=String(req.body?.sportTag||'').trim(),mediaUrl=req.body?.mediaUrl?String(req.body.mediaUrl):undefined,mediaType=req.body?.mediaType==='video'?'video':'image';if(!content&&!mediaUrl)return res.status(400).json({error:'Добавьте текст или фотографию.'});if(content.length>2000)return res.status(400).json({error:'Слишком длинный текст.'});const id=`post_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,post={id,authorId:decoded.uid,authorName:user.name||'Спортсмен',authorAvatar:user.avatar||'',authorPlan:user.subscriptionPlan||'free',sportTag,content,mediaUrl,mediaType:mediaUrl?mediaType:undefined,likes:[],commentsCount:0,comments:[],createdAt:new Date().toISOString()};await db.collection('feed').doc(id).create(post);return res.status(200).json({ok:true,post});}catch(e){console.error('[feed-create]',e);return res.status(e.code?.startsWith?.('auth/')?401:500).json({error:e.message||'Не удалось опубликовать запись'});}
}
